<testExecutions version="1">
<file path="src\tests\ImportarPlanilhaSinistro.spec.tsx">
<testCase name="Cadastro CSV" duration="388" />
<testCase name="Cadastro CSV erro" duration="248" />
<testCase name="Cadastro CSV vazio" duration="117" />
<testCase name="Cadastro sem enviar CSV" duration="60" />
<testCase name="Sem o provider" duration="42">
<failure message="Error"><![CDATA[Error: expect(received).toThrow(expected)

Expected message: &quot;useAcidentes must be used within a AcidentesProvider&quot;

Received function did not throw
    at toThrow (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:147:7)
    at call (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at Generator.tryCatch (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at Generator._invoke [as next] (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at asyncGeneratorStep (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at asyncGeneratorStep (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at _next (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at new Promise (&lt;anonymous&gt;)
    at Object.&lt;anonymous&gt; (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\src\tests\ImportarPlanilhaSinistro.spec.tsx:2:1)
    at Promise.then.completed (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\utils.js:226:10)
    at _callCircusTest (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\run.js:297:40)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at processTimers (node:internal/timers:512:7)
    at _runTest (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\run.js:233:3)
    at _runTestsForDescribeBlock (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\run.js:135:9)
    at run (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\run.js:68:3)
    at runAndTransformResultsToJestFormat (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:122:21)
    at jestAdapter (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:79:19)
    at runTestInternal (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-runner\build\runTest.js:367:16)
    at runTest (C:\Users\migue\Documents\2023.1_Unb\MDS\2023.1-Dnit-Front\node_modules\jest-cli\node_modules\jest-runner\build\runTest.js:444:34)]]></failure>
</testCase>
</file>
</testExecutions>